### ISSUE TITLE
Thanks! + Build fail on Mac

### ISSUE THREAD

**Issue by wbpaley** [mira-screen-share/sharer#61]
This is an amazing and useful contribution; thank you!

I brew-installed ffmpeg and tried to compile it on a Macbook pro M2 running Sonoma 14.2, in RustRover and also from the terminal.

In RustRover I get:
```
error: failed to run custom build command for `ac-ffmpeg v0.17.4 (https://github.com/mira-screen-share/rust-ac-ffmpeg?branch=dev#8c469771)`
```

The command line gives me:
```
brad@Hutchins sharer-main % cargo run --release
... (many compiling+ lines elided)
  error occurred: Command env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "/opt/homebrew/Cellar/ffmpeg/7.0.1/include" "-Wall" "-Wextra" "-o" "/Users/brad/BradsExploratoryProjects/sharer-main/target/release/build/ac-ffmpeg-97185c71929fef0d/out/src/codec/mod.o" "-c" "src/codec/mod.c" with args "cc" did not execute successfully (status code exit status: 1).
```

Any hints?

If my newbie guess that an iPhone target is holding up the works is true, I don't need it; I just need to run it on my Macbook. So I could disable that target?

Thanks!
Brad

**Comment by kevinmershon** [comment]
@wbpaley Maybe you already solved this and never came back to the issue, but according to one of the underlying deps the latest ffmpeg it depends on is ffmpeg v5 https://github.com/angelcam/rust-ac-ffmpeg?tab=readme-ov-file#requirements

**Comment by wbpaley** [comment]
Great! Thank you.

I just paused this sub-project and went to others that weren’t blocking me. I’ll try this next week and report back (pushing for demo Thursday).





.
